# Generated by Django 3.2 on 2022-12-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
